---
title: "Passwords"
author: "Joseph Pope"
date: "1/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Passwords 

https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-01-14/readme.md



```{r}
library(tidyverse)
library(here)
library(janitor)
library(ggthemes)
options(scipen = 9999)

passwords <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-14/passwords.csv')



```
```{r}
passwords %>%
  count(category) %>%
  arrange(desc(n))
```


Find types of passwords, lowercase, upper, both, symbols, digits, etc. 
```{r}



passwords3 <- passwords %>%
  mutate(pwd_types = ifelse(password == '1234',
                            "my_luggage_combo", 
                            "other_passwords"))
```

```{r}
passwords2 <- passwords %>%
  mutate(online_crack_sec = case_when(
    time_unit == "minutes" ~ value * 60,
    time_unit == "hours" ~ value * 60 * 60, 
    time_unit == "days" ~ value * 60 * 60 * 24,
    time_unit == "weeks" ~ value * 60 * 60 * 24 * 7,
    time_unit == "months" ~ value * 60 * 60 * 24 * 7 * 4,
    time_unit == "years" ~ value * 60 * 60 * 24 * 7 * 52,
    TRUE ~ value
  ),
    length = nchar(password)) %>%
  drop_na(strength, length)

```



```{r}

p <- ggplot(passwords2, aes(strength, length, color=factor(category))) + 
  geom_point(na.rm = TRUE) + 
  # geom_jitter(width = 0.2, height = 0.2) + 
  geom_smooth(method = "lm", se = FALSE, color = "grey44", size = .8, linewidth = 11) + 
  facet_wrap(~ category) 

# + 
#   theme_fivethirtyeight(base_family = "Roboto", base_size = 10) + 

```

```{r}
p +  theme(legend.position="None",
           panel.background = element_blank(), 
           plot.title = element_text(hjust = 0.5),
           plot.subtitle = element_text(hjust = 0.5),
           text = element_text(family = "Roboto"), 
           axis.ticks = element_blank(), 
           strip.background = element_rect(fill="royalblue"), 
           strip.text = element_text(face = "bold", color = "white"),
           axis.title = element_text(family = "Courier", size = 8)) + 
    labs(title = "Strength of Password Relative to Length of Password",
      subtitle = "A mix of alpha numerics and symbols are generally preferred",
      caption = "Joseph Pope") + 
  ylab("# of characters in Password") + 
  xlab("Strength of Password")
```

Save ggplot to image on disk 
```{r}
ggsave("passwords.png", p)
```

