---
title: "Tweet Notebook"
output: html_notebook
---

```{r rtweet, include=FALSE}
library(rtweet)
```


# 2020-4-27 GDPR 
```{r gdpr}
rtweet::post_tweet(media = "17_gdpr/gdpr.png",
                   status = "Used textmineR to explore GDPR summary text violations. Results of LDA topic modeling in scatterplot, showing coherence vs. prevalence. #rstats #TidyTuesday")

```
# 2020-05-04 Broadway Shows 
```{r}
rtweet::post_tweet(media = "18_broadway/bway.png",
                   status = "Tried a few different things and ended up with a basic scatterplot. Y-axis is total share of weekly gross $$$. #rstats #TidyTuesday")
```

# 2020-05-24 Beach Volleyball 
```{r}
rtweet::post_tweet(media = "21_beach_volleyball/vball.png",
                   status = "'Solarized' seemed like an appropriate theme to handle beach volleyball data. #rstats #TidyTuesday")
```

# 2020-05-31 Cocktails 
```{r}
rtweet::post_tweet(media = "22_cocktails/cocktails.png",
                   status = "#TidyTuesday...after dark! Visualized correlation pairs of cocktails and graphed the relationships. #rstats")
```

# 2020-06-04 Marble Racing 

```{r}
rtweet::post_tweet(media = "23_marbles/marbles.png",
                   status = "Manually created this dumbell chart to show slow and fast members of the same team. Snowy is just really holding Snowflake back. #sad #TidyTuesday #rstats")
```

# 2020-06-15 Firsts African Americans
```{r}
rtweet::post_tweet(media = "24_black_achievements/firsts.png", 
                   status = "Tried several things, but think this one shows impact of Civil War and Civil Rights Act, both before and after they occur. #TidyTuesday #rstats https://github.com/joepope44/tidytuesday/blob/master/24_black_achievements/black_achievements.R")
```

# 2020-06-23 Juneteenth
```{r}
rtweet::post_tweet(media = "25_juneteenth/routes.png", 
                   status = "Tried and failed so many things here. My first time building a map with this kind of detail. Very challenging! #TidyTuesday #rstats https://github.com/joepope44/tidytuesday/tree/master/25_juneteenth")
```

# 2020-07-01 X-Men Claremont Run 
```{r}
rtweet::post_tweet(media = "27_xmen/xmen.png", 
                   status = "Perfect time to use COMIC SANS! #TidyTuesday #rstats @ClaremontRun https://github.com/joepope44/tidytuesday/tree/master/27_xmen")
```

